### PR TITLE
Detailed design files

### PR DESCRIPTION
**Pull request by AJ-Work-Smoothie**
Making a circuit board from GERBERS is quite difficult, especially when the border is not complete. This commit adds easily-useable DXFs, Fusion 360 3D models/DXF origins, and an Eagle Library for ease of implementation.

### CODE REVIEW

**Comment by AdamCummick** [comment]
Thanks @AJ-Work-Smoothie. I'm sending this over to our Mechanical Engineer to review. 

In the meantime could you shoot me an email at adamc@facts-eng.com.

**Comment by AdamCummick** [comment]
Everything looks good, however our mechanical engineer recommended increasing the depth of these cutouts to 1.25mm to avoid potential interference with the latches.
image

**Comment by AJ-Work-Smoothie** [comment]
I started investigating further and I started seeing problems show up, and why the original gerber wasn't "watertight".  If you make a vertical line from the bottom right corner of the PCB to the top right (blue), this point (red) is off by 0.003mm. 

sh1
sh2


If you draw a line from the right side of the PCB over to the left (blue), the line is perfectly horizontal. The line attachments on the right side of the board coincide with the line, however, the points on the left side are off by distances of 0.01mm. 

sh3
sh4

I will square these off and push a repaired dxf

**Comment by AJ-Work-Smoothie** [comment]
The DXF underwent extensive surgery and has been re-drawn with everything being perfectly horizontal/vertical, and now it is watertight and imports into eagle properly. 

Arcs have been added to the slots where the latches go, the greatest distance is 1.256mm. 

Please reverify as I only have the crooked gerber as a reference!

sh5

**Comment by AdamCummick** [comment]
Everything looks good on this round. Thanks for adding these files!

**Pull request merged**
